spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route to user service
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
          filters:
            - "RewritePath=/users(?<segment>/?.*), /api/users${segment}"

        # Route to product service
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
          filters:
            - "RewritePath=/products(?<segment>/?.*), /api/products${segment}"

        # Route to order service
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          filters:
            - "RewritePath=/orders(?<segment>/?.*), /api/orders${segment}"

        # Route to cart (inside order service)
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/cart/**
          filters:
            - "RewritePath=/cart(?<segment>/?.*), /api/cart${segment}"

#        - id: eureka-server-ui
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**
#          filters:
#            - StripPrefix=1


server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
#server:
#  port: 8080
#
#logging:
#  level:
#    root: INFO
#    org.springframework.cloud.gateway: TRACE
#
#spring:
#  application:
#    name: gateway-service
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    gateway:
#      enabled: true
#  security:
#    enabled: false
#
