spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_service_db
    username: ecomuser
    password: secret123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rolling policy:
      max-file-size: 5MB
      max-history: 5
management:
  tracing:
    sampling:
      probability: 1.0
